registerUser:
	python3 sbam.py new-user myUser somesocial
registerPkg:
	python3 sbam.py new-pkg myUser myPkg ./pkgStorage/myPkg
updatePkg:
	python3 sbam.py update-pkg myPkg myUser ./pkgStorage/myPkg
downloadPkg:
	python3 sbam.py download-pkg myPkg ./pkgStorage 0